language: node_js

node_js:
  - "10"
  - "9"
  - "8"

script:
  - npm run coveralls

notifications:
  email:
    on_success: never
    on_failure: never
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
